// Code generated by protoc-gen-go. DO NOT EDIT.
// source: peer.proto

package bftmessages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgType int32

const (
	MsgType_ClientRequest  MsgType = 0
	MsgType_ClientResponse MsgType = 1
	MsgType_PrePrepare     MsgType = 2
	MsgType_Prepare        MsgType = 3
	MsgType_Commit         MsgType = 4
	MsgType_Checkpoint     MsgType = 5
	MsgType_Probe          MsgType = 6
	MsgType_ProbeAck       MsgType = 7
	MsgType_NewConfig      MsgType = 8
	MsgType_SyncState      MsgType = 9
)

var MsgType_name = map[int32]string{
	0: "ClientRequest",
	1: "ClientResponse",
	2: "PrePrepare",
	3: "Prepare",
	4: "Commit",
	5: "Checkpoint",
	6: "Probe",
	7: "ProbeAck",
	8: "NewConfig",
	9: "SyncState",
}

var MsgType_value = map[string]int32{
	"ClientRequest":  0,
	"ClientResponse": 1,
	"PrePrepare":     2,
	"Prepare":        3,
	"Commit":         4,
	"Checkpoint":     5,
	"Probe":          6,
	"ProbeAck":       7,
	"NewConfig":      8,
	"SyncState":      9,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}

func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_055ae5a865fc1c9e, []int{0}
}

type PeerMessage struct {
	FromNodeId           int32            `protobuf:"varint,1,opt,name=fromNodeId,proto3" json:"fromNodeId,omitempty"`
	MsgId                int32            `protobuf:"varint,2,opt,name=msgId,proto3" json:"msgId,omitempty"`
	EpochId              int32            `protobuf:"varint,3,opt,name=epochId,proto3" json:"epochId,omitempty"`
	Type                 MsgType          `protobuf:"varint,4,opt,name=type,proto3,enum=bftmessages.MsgType" json:"type,omitempty"`
	AttachedData         []byte           `protobuf:"bytes,5,opt,name=attachedData,proto3" json:"attachedData,omitempty"`
	Auth                 []*Authenticator `protobuf:"bytes,6,rep,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PeerMessage) Reset()         { *m = PeerMessage{} }
func (m *PeerMessage) String() string { return proto.CompactTextString(m) }
func (*PeerMessage) ProtoMessage()    {}
func (*PeerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_055ae5a865fc1c9e, []int{0}
}

func (m *PeerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerMessage.Unmarshal(m, b)
}
func (m *PeerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerMessage.Marshal(b, m, deterministic)
}
func (m *PeerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerMessage.Merge(m, src)
}
func (m *PeerMessage) XXX_Size() int {
	return xxx_messageInfo_PeerMessage.Size(m)
}
func (m *PeerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PeerMessage proto.InternalMessageInfo

func (m *PeerMessage) GetFromNodeId() int32 {
	if m != nil {
		return m.FromNodeId
	}
	return 0
}

func (m *PeerMessage) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *PeerMessage) GetEpochId() int32 {
	if m != nil {
		return m.EpochId
	}
	return 0
}

func (m *PeerMessage) GetType() MsgType {
	if m != nil {
		return m.Type
	}
	return MsgType_ClientRequest
}

func (m *PeerMessage) GetAttachedData() []byte {
	if m != nil {
		return m.AttachedData
	}
	return nil
}

func (m *PeerMessage) GetAuth() []*Authenticator {
	if m != nil {
		return m.Auth
	}
	return nil
}

type CertificateMessage struct {
	Initialized          bool           `protobuf:"varint,1,opt,name=initialized,proto3" json:"initialized,omitempty"`
	CntPrepared          int32          `protobuf:"varint,2,opt,name=cntPrepared,proto3" json:"cntPrepared,omitempty"`
	Certificates         []*PeerMessage `protobuf:"bytes,3,rep,name=certificates,proto3" json:"certificates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CertificateMessage) Reset()         { *m = CertificateMessage{} }
func (m *CertificateMessage) String() string { return proto.CompactTextString(m) }
func (*CertificateMessage) ProtoMessage()    {}
func (*CertificateMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_055ae5a865fc1c9e, []int{1}
}

func (m *CertificateMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertificateMessage.Unmarshal(m, b)
}
func (m *CertificateMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertificateMessage.Marshal(b, m, deterministic)
}
func (m *CertificateMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertificateMessage.Merge(m, src)
}
func (m *CertificateMessage) XXX_Size() int {
	return xxx_messageInfo_CertificateMessage.Size(m)
}
func (m *CertificateMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CertificateMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CertificateMessage proto.InternalMessageInfo

func (m *CertificateMessage) GetInitialized() bool {
	if m != nil {
		return m.Initialized
	}
	return false
}

func (m *CertificateMessage) GetCntPrepared() int32 {
	if m != nil {
		return m.CntPrepared
	}
	return 0
}

func (m *CertificateMessage) GetCertificates() []*PeerMessage {
	if m != nil {
		return m.Certificates
	}
	return nil
}

type PayloadNewConfig struct {
	Members              []int32  `protobuf:"varint,1,rep,packed,name=members,proto3" json:"members,omitempty"`
	Leader               int32    `protobuf:"varint,2,opt,name=leader,proto3" json:"leader,omitempty"`
	DigestState          []byte   `protobuf:"bytes,3,opt,name=digestState,proto3" json:"digestState,omitempty"`
	DigestP              []byte   `protobuf:"bytes,4,opt,name=digestP,proto3" json:"digestP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayloadNewConfig) Reset()         { *m = PayloadNewConfig{} }
func (m *PayloadNewConfig) String() string { return proto.CompactTextString(m) }
func (*PayloadNewConfig) ProtoMessage()    {}
func (*PayloadNewConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_055ae5a865fc1c9e, []int{2}
}

func (m *PayloadNewConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayloadNewConfig.Unmarshal(m, b)
}
func (m *PayloadNewConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayloadNewConfig.Marshal(b, m, deterministic)
}
func (m *PayloadNewConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayloadNewConfig.Merge(m, src)
}
func (m *PayloadNewConfig) XXX_Size() int {
	return xxx_messageInfo_PayloadNewConfig.Size(m)
}
func (m *PayloadNewConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PayloadNewConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PayloadNewConfig proto.InternalMessageInfo

func (m *PayloadNewConfig) GetMembers() []int32 {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *PayloadNewConfig) GetLeader() int32 {
	if m != nil {
		return m.Leader
	}
	return 0
}

func (m *PayloadNewConfig) GetDigestState() []byte {
	if m != nil {
		return m.DigestState
	}
	return nil
}

func (m *PayloadNewConfig) GetDigestP() []byte {
	if m != nil {
		return m.DigestP
	}
	return nil
}

type PayloadSyncState struct {
	Clients              []int32             `protobuf:"varint,1,rep,packed,name=clients,proto3" json:"clients,omitempty"`
	Certificate          *CertificateMessage `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
	NewConfigMessage     *PeerMessage        `protobuf:"bytes,3,opt,name=newConfigMessage,proto3" json:"newConfigMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PayloadSyncState) Reset()         { *m = PayloadSyncState{} }
func (m *PayloadSyncState) String() string { return proto.CompactTextString(m) }
func (*PayloadSyncState) ProtoMessage()    {}
func (*PayloadSyncState) Descriptor() ([]byte, []int) {
	return fileDescriptor_055ae5a865fc1c9e, []int{3}
}

func (m *PayloadSyncState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayloadSyncState.Unmarshal(m, b)
}
func (m *PayloadSyncState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayloadSyncState.Marshal(b, m, deterministic)
}
func (m *PayloadSyncState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayloadSyncState.Merge(m, src)
}
func (m *PayloadSyncState) XXX_Size() int {
	return xxx_messageInfo_PayloadSyncState.Size(m)
}
func (m *PayloadSyncState) XXX_DiscardUnknown() {
	xxx_messageInfo_PayloadSyncState.DiscardUnknown(m)
}

var xxx_messageInfo_PayloadSyncState proto.InternalMessageInfo

func (m *PayloadSyncState) GetClients() []int32 {
	if m != nil {
		return m.Clients
	}
	return nil
}

func (m *PayloadSyncState) GetCertificate() *CertificateMessage {
	if m != nil {
		return m.Certificate
	}
	return nil
}

func (m *PayloadSyncState) GetNewConfigMessage() *PeerMessage {
	if m != nil {
		return m.NewConfigMessage
	}
	return nil
}

func init() {
	proto.RegisterEnum("bftmessages.MsgType", MsgType_name, MsgType_value)
	proto.RegisterType((*PeerMessage)(nil), "bftmessages.PeerMessage")
	proto.RegisterType((*CertificateMessage)(nil), "bftmessages.CertificateMessage")
	proto.RegisterType((*PayloadNewConfig)(nil), "bftmessages.PayloadNewConfig")
	proto.RegisterType((*PayloadSyncState)(nil), "bftmessages.PayloadSyncState")
}

func init() { proto.RegisterFile("peer.proto", fileDescriptor_055ae5a865fc1c9e) }

var fileDescriptor_055ae5a865fc1c9e = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x3d, 0x6f, 0xdb, 0x30,
	0x14, 0xac, 0xe2, 0xef, 0x27, 0xd9, 0x60, 0x5f, 0x83, 0x42, 0xc8, 0xd0, 0x0a, 0x9e, 0x8c, 0x0e,
	0x1e, 0xdc, 0xb5, 0x8b, 0xeb, 0x2c, 0x1e, 0x12, 0x08, 0x4c, 0xa7, 0x6e, 0xb4, 0xf4, 0x6c, 0x13,
	0xb1, 0x44, 0x95, 0x64, 0x50, 0xb8, 0x53, 0x7f, 0x45, 0xe7, 0xfe, 0x89, 0xfe, 0x9a, 0xfe, 0x99,
	0x42, 0xb4, 0xe4, 0xd0, 0x08, 0xd0, 0x4d, 0x77, 0x3a, 0x3e, 0xdc, 0xdd, 0x23, 0x01, 0x2a, 0x22,
	0x3d, 0xaf, 0xb4, 0xb2, 0x0a, 0xc3, 0xcd, 0xd6, 0x16, 0x64, 0x8c, 0xd8, 0x91, 0xb9, 0x79, 0x23,
	0x9e, 0xec, 0x9e, 0x4a, 0x2b, 0x33, 0x61, 0x55, 0xa3, 0x98, 0xfe, 0x0d, 0x20, 0x4c, 0x89, 0xf4,
	0xdd, 0x49, 0x85, 0xef, 0x00, 0xb6, 0x5a, 0x15, 0xf7, 0x2a, 0xa7, 0x75, 0x1e, 0x07, 0x49, 0x30,
	0xeb, 0x71, 0x8f, 0xc1, 0x6b, 0xe8, 0x15, 0x66, 0xb7, 0xce, 0xe3, 0x2b, 0xf7, 0xeb, 0x04, 0x30,
	0x86, 0x01, 0x55, 0x2a, 0xdb, 0xaf, 0xf3, 0xb8, 0xe3, 0xf8, 0x16, 0xe2, 0x0c, 0xba, 0xf6, 0x58,
	0x51, 0xdc, 0x4d, 0x82, 0xd9, 0x64, 0x71, 0x3d, 0xf7, 0x0c, 0xcd, 0xef, 0xcc, 0xee, 0xcb, 0xb1,
	0x22, 0xee, 0x14, 0x38, 0x85, 0x48, 0x58, 0x2b, 0xb2, 0x3d, 0xe5, 0xb7, 0xc2, 0x8a, 0xb8, 0x97,
	0x04, 0xb3, 0x88, 0x5f, 0x70, 0x38, 0x87, 0x6e, 0x1d, 0x22, 0xee, 0x27, 0x9d, 0x59, 0xb8, 0xb8,
	0xb9, 0x98, 0xb6, 0xf4, 0xd3, 0x71, 0xa7, 0x9b, 0xfe, 0x0a, 0x00, 0x57, 0xa4, 0xad, 0xdc, 0xd6,
	0x34, 0xb5, 0x21, 0x13, 0x08, 0x65, 0x29, 0xad, 0x14, 0x07, 0xf9, 0x83, 0x4e, 0x29, 0x87, 0xdc,
	0xa7, 0x6a, 0x45, 0x56, 0xda, 0x54, 0x53, 0x25, 0x34, 0xb5, 0x61, 0x7d, 0x0a, 0x3f, 0x41, 0x94,
	0x3d, 0x4f, 0x36, 0x71, 0xc7, 0x59, 0x8a, 0x2f, 0x2c, 0x79, 0xc5, 0xf2, 0x0b, 0xf5, 0xf4, 0x67,
	0x00, 0x2c, 0x15, 0xc7, 0x83, 0x12, 0xf9, 0x3d, 0x7d, 0x5f, 0xa9, 0x72, 0x2b, 0x77, 0x75, 0x8b,
	0x05, 0x15, 0x1b, 0xd2, 0x26, 0x0e, 0x92, 0x4e, 0xdd, 0x62, 0x03, 0xf1, 0x2d, 0xf4, 0x0f, 0x24,
	0x72, 0xd2, 0x8d, 0x93, 0x06, 0xd5, 0x36, 0x73, 0xb9, 0x23, 0x63, 0x1f, 0xac, 0xb0, 0xe4, 0xba,
	0x8f, 0xb8, 0x4f, 0xd5, 0x33, 0x4f, 0x30, 0x75, 0x2b, 0x88, 0x78, 0x0b, 0xa7, 0x7f, 0x9e, 0x2d,
	0x3c, 0x1c, 0xcb, 0xec, 0x2c, 0xcf, 0x0e, 0x92, 0x4a, 0x7b, 0xb6, 0xd0, 0x40, 0x5c, 0x42, 0xe8,
	0x25, 0x70, 0x3e, 0xc2, 0xc5, 0xfb, 0x8b, 0xb8, 0x2f, 0x9b, 0xe6, 0xfe, 0x19, 0xbc, 0x05, 0x56,
	0xb6, 0x61, 0x1b, 0x81, 0xb3, 0xfc, 0xbf, 0xda, 0x5e, 0x9c, 0xf8, 0xf0, 0x3b, 0x80, 0x41, 0x73,
	0x73, 0xf0, 0x35, 0x8c, 0x57, 0xce, 0x1f, 0xa7, 0x6f, 0x4f, 0x64, 0x2c, 0x7b, 0x85, 0x08, 0x93,
	0x96, 0x32, 0x95, 0x2a, 0x0d, 0xb1, 0x00, 0x27, 0x00, 0xa9, 0xa6, 0x66, 0x75, 0xec, 0x0a, 0x43,
	0x18, 0xb4, 0xa0, 0x83, 0x00, 0xfd, 0x95, 0x2a, 0x0a, 0x69, 0x59, 0xb7, 0x16, 0xae, 0xf6, 0x94,
	0x3d, 0x56, 0x4a, 0x96, 0x96, 0xf5, 0x70, 0x04, 0xbd, 0x54, 0xab, 0x0d, 0xb1, 0x3e, 0x46, 0x30,
	0x74, 0x9f, 0xcb, 0xec, 0x91, 0x0d, 0x70, 0x0c, 0xa3, 0xf3, 0xde, 0xd8, 0xb0, 0x86, 0xe7, 0x0e,
	0xd9, 0xe8, 0xf3, 0xf8, 0xab, 0xff, 0xf0, 0x36, 0x7d, 0xf7, 0xd4, 0x3e, 0xfe, 0x0b, 0x00, 0x00,
	0xff, 0xff, 0x0c, 0x65, 0x4e, 0x28, 0x9a, 0x03, 0x00, 0x00,
}
